name: 3-test-django-secrets

on:
  workflow_dispatch: # Means I can run this at any time
  # push:
  #   branch:
  #     -main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        DJANGO_DEBUG: 0
        DATABASE_URL: ${{secrets.TEST_NEON_DATABASE_URL}}
        # DJANGO_SECRET_KEY: fake_var
    steps:
      -name: Checkout Code
        uses: actions/checkout@v4
      -name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      -name: Setup Django Secret Key
        run: |
          GENERATED_KEY=$(openssl rand -base64 32)
          echo "DJANGO_SECRET_KEY=$GENERATED_KEY" >>$GITHUB_ENV
      -name: Install Requirements
      run: |
        python -m pip install pip --upgrade
        python -m pip install -r requirements.txt
      -name: Django Test Requirements
      working-directory: ./src
      run: |
        python manage.py test

