# Generated by Django 5.1.1 on 2024-10-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("groups", models.ManyToManyField(to="auth.group")),
                (
                    "permission",
                    models.ManyToManyField(
                        limit_choices_to={
                            "codename__in": ["advanced", "pro", "basic", "basic_ai"],
                            "content_type__app_label": "subscriptions",
                        },
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("advanced", "Advanced Permissions"),
                    ("pro", "Pro Permissions"),
                    ("basic", "Basic Permissions"),
                    ("basic_ai", "Basic AI Permissions"),
                ],
            },
        ),
    ]
