# Generated by Django 5.1.1 on 2024-10-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "permissions": [
                    ("advanced", "Advanced Permissions"),
                    ("pro", "Pro Permissions"),
                    ("basic", "Basic Permissions"),
                    ("basic_ai", "Basic AI Permissions"),
                ]
            },
        ),
    ]
