# Generated by Django 5.1.1 on 2024-10-29 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_subscription_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="permission",
            new_name="permissions",
        ),
    ]
