# Generated by Django 5.1.1 on 2024-11-04 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_subscriptionprice_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["order", "featured", "-updated"],
                "permissions": [
                    ("advanced", "Advanced Permissions"),
                    ("pro", "Pro Permissions"),
                    ("basic", "Basic Permissions"),
                    ("basic_ai", "Basic AI Permissions"),
                ],
            },
        ),
        migrations.RemoveField(
            model_name="subscriptionprice",
            name="featured",
        ),
        migrations.RemoveField(
            model_name="subscriptionprice",
            name="order",
        ),
        migrations.RemoveField(
            model_name="subscriptionprice",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="subscriptionprice",
            name="updated",
        ),
        migrations.AddField(
            model_name="subscription",
            name="featured",
            field=models.BooleanField(
                default=True, help_text="Featured on Django Pricing page"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="order",
            field=models.IntegerField(
                default=-1, help_text="Order on Django Pricing Page"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
