# Generated by Django 5.1.1 on 2024-11-04 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={
                "ordering": ["Subscription__order", "order", "featured", "-updated"]
            },
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="featured",
            field=models.BooleanField(
                default=True, help_text="Featured on Django Pricing page"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="order",
            field=models.IntegerField(
                default=-1, help_text="Order on Django Pricing Page"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
