# Generated by Django 5.1.1 on 2024-11-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0010_alter_subscriptionprice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionprice",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="Specify the features of each plan",
                null=True,
            ),
        ),
    ]
