# Generated by Django 5.1.1 on 2024-11-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0011_subscriptionprice_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionprice",
            name="features",
        ),
        migrations.AddField(
            model_name="subscription",
            name="features",
            field=models.TextField(
                blank=True, help_text="Specify the features of each plan", null=True
            ),
        ),
    ]
