# Generated by Django 5.1.1 on 2024-11-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0012_remove_subscriptionprice_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="Specify the features of each plan with each feature on a new line!",
                null=True,
            ),
        ),
    ]
