# Generated by Django 5.1.1 on 2024-11-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscriptions",
            "0013_subscription_subtitle_alter_subscription_features",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
