# Generated by Django 5.1.1 on 2024-11-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0017_usersubscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("trialing", "Trialing"),
                    ("incomplete", "Incomplete"),
                    ("incomplete_expired", "Incomplete Expired"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("unpaid", "Unpaid"),
                    ("paused", "Paused"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
