# Generated by Django 5.1.1 on 2024-11-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscriptions",
            "0018_usersubscription_cancel_at_period_end_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("trialing", "Trialing"),
                    ("incomplete", "Incomplete"),
                    ("incomplete_expired", "Incomplete Expired"),
                    ("past_due", "Past Due"),
                    ("canceled", "Cancelled"),
                    ("unpaid", "Unpaid"),
                    ("paused", "Paused"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
