# Generated by Django 5.1.3 on 2024-12-06 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0019_alter_usersubscription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionprice",
            name="Subscription",
            field=models.ForeignKey(
                help_text="The subscription product associated with this price.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="featured",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if this price is featured on the Django Pricing Page.",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="interval",
            field=models.CharField(
                choices=[("month", "Monthly"), ("year", "Annually")],
                default="month",
                help_text="The billing interval for the subscription price.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="order",
            field=models.IntegerField(
                default=-1,
                help_text="Display order on the Django Pricing Page.",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=9.99,
                help_text="The price amount in the specified currency.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="stripe_id",
            field=models.CharField(
                blank=True,
                help_text="The Stripe ID for the price object.",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The timestamp when the price was created.",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The timestamp when the price was last updated.",
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("trialing", "Trialling"),
                    ("incomplete", "Incomplete"),
                    ("incomplete_expired", "Incomplete Expired"),
                    ("past_due", "Past Due"),
                    ("canceled", "Cancelled"),
                    ("unpaid", "Unpaid"),
                    ("paused", "Paused"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
