name: scheduled-production-workflows
on:
  workflow_dispatch: # Means I can run this at any time
  schedule:
    - cron: '0 1 20 * * *' # Every 20th day of the month at 1:00 AM UTC
    - cron: '1 0 1 * * *'  # 1st day of the month at 0:01 AM UTC

jobs:
  tidy_up:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: 0
      STRIPE_TEST_KEY_OVERRIDE: 1
      STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
      NEON_API_KEY: ${{secrets.NEON_API_KEY}}
      NEON_PROJECT_ID: ${{secrets.NEON_PROJECT_ID}}
      NEON_PROD_BRANCH: "main"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      
      - name: Install Neon CLI
        run: |
          npm install -g neonctl


      - name: Grab Database URL
        run: |
          DB_CONNECTION_STRING = $(neonctl connections-string --branch "${{env.NEON_PROD_BRANCH}}" --project-id "${{env.NEON_PROJECT_ID}}")
          echo "DATABASE_URL=$DB_CONNECTION_STRING" >>$GITHUB_ENV

      - name: Setup Django Secret Key
        run: |
          GENERATED_KEY=$(openssl rand -base64 32)
          echo "DJANGO_SECRET_KEY=$GENERATED_KEY" >>$GITHUB_ENV
      - name: Install Requirements
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt
      
      - name: Make Django DB Migrations
        working-directory: ./src
        run: |
          python manage.py migrate
     
      - name: User Syncronisation Command
      if: github.event.schedule == '1 0 1 * * *'
      working-directory: ./src
      run: |
        python manage.py sync_user_subscriptions --verbose --from-days 0 --to-days 1
      
      - name: Clear Dangling Stripe Subscriptions Commands
      if: github.event.schedule == '0 1 20 * * *'
      working-directory: ./src
      run: |
        python manage.py sync_user_subscriptions --clear-dangling
