name: django-tests-with-db-neon
on:
  workflow_dispatch:
  push:
    branches:
      - feat/hotfix-ci_cd_yamls

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: 0
      NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
      NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
      NEON_PROD_BRANCH: "main"
      NEON_GITHUB_BRANCH: "gh-test"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11'

      - name: Install Neon CLI
        run: npm install -g neonctl      
      - name: Delete previous branch version
        continue-on-error: true
        run: |
          neonctl branches delete "${{ env.NEON_GITHUB_BRANCH }}" --project-id "${{ env.NEON_PROJECT_ID }}"
      
      - name: Create new branch version
        run: |
          neonctl branches create --name "${{ env.NEON_GITHUB_BRANCH }}" --parent "${{ env.NEON_PROD_BRANCH }}" --project-id "${{ env.NEON_PROJECT_ID }}"

      - name: Grab new branch database url
        run: |
          DB_CONNECTION_STRING=$(neonctl connection-string --branch "${{ env.NEON_GITHUB_BRANCH }}" --project-id "${{ env.NEON_PROJECT_ID }}")
          echo "DATABASE_URL=$DB_CONNECTION_STRING" >> $GITHUB_ENV

      - name: Setup Django Secret Key
        run: |
          GENERATED_KEY=$(openssl rand -base64 32)
          echo "DJANGO_SECRET_KEY=$GENERATED_KEY" >> $GITHUB_ENV
      
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install Dependencies with Poetry
        run: |
          poetry install --no-interaction --no-ansi
      
      - name: Make Django DB Migrations
        working-directory: ./src
        run: |
          python manage.py migrate
      
      - name: Run Django Tests
        working-directory: ./src
        run: |
          python manage.py test
      
      - name: Clean Up Test branch
        continue-on-error: true
        run: |
          neonctl branches delete "${{ env.NEON_GITHUB_BRANCH }}" --project-id "${{ env.NEON_PROJECT_ID }}"